
channels:
  - conda-forge

dependencies:
  - python
  - fenics-dolfinx >= 0.11
  - scifem >= 0.22.0
  - mpich
  - gmsh
  - python-gmsh
  - pyvista
  - adios2
  - pdbpp
  - pip
  - numpy >= 2.0
  - scipy
  - matplotlib
  - tqdm
  - pytest
  - ruff
